const ActionTypes = {
    CHANGE_PAGE: "CHANGE_PAGE",
    SHOW_DOCUMENT: "SHOW_DOCUMENT",
    FILTER_DOCUMENT_LIST: "FILTER_DOCUMENT_LIST",
    SORT_DOCUMENTS: "SORT_DOCUMENTS",
    DELETE_DOCUMENT:"DELETE_DOCUMENT",
    UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
    CHANGE_DOCTYPE: "CHANGE_DOCTYPE",
    CHANGE_UPLOADTYPE: "CHANGE_UPLOADTYPE",
    LOAD_DOCUMENTS_SUCCESS: "LOAD_DOCUMENTS_SUCCESS",
    LOAD_DOCUMENTS_FAILURE: "LOAD_DOCUMENTS_FAILURE",
    LOAD_TYPES_SUCCESS: "LOAD_TYPES_SUCCESS",
    LOAD_TYPES_FAILURE: "LOAD_TYPES_FAILURE"
};

export default ActionTypes;